install:
	pip install --upgrade pip &&\
	    pip install -r requirements/freeze-requirements.txt
	
format:
	black *.py

lint: 
	pylint --disable=R,C --errors-only bikeshare_model/*.py

test:
	python3 -m pytest ./bikeshare_model/tests/test_*.py

all: install lint test format